// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Todo.DataModel;

namespace WebApi.Todo.DataModel.Migrations
{
    [DbContext(typeof(TodosDbContext))]
    [Migration("20201006122756_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Todo.DataModel.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("Title")
                        .HasMaxLength(20);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoList");

                    b.HasData(
                        new { Id = 1, Completed = false, Description = "Go to the market and buy vegtables, bread, gin, cigarettes", Title = "Buy groceries", UserId = 1 },
                        new { Id = 2, Completed = false, Description = "Watch breaking bad, the witcher and narcos", Title = "Finally watch all the tv shows that you have wanted ", UserId = 1 }
                    );
                });

            modelBuilder.Entity("WebApi.Todo.DataModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new { Id = 1, FirstName = "Nikola", LastName = "Jovanovski", Password = "(?\\?-??3#>L?q", UserName = "NikolaJ" }
                    );
                });

            modelBuilder.Entity("WebApi.Todo.DataModel.TodoList", b =>
                {
                    b.HasOne("WebApi.Todo.DataModel.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
